### ISSUE TITLE
Can't import any comics

### ISSUE THREAD

**Issue by g2744092** [hmhrex/tenma-docker#4]
I created a docker container: 
`docker create --name=tenma -v /mnt/Data/Comics:/tenma/files -v  /mnt/Config/Tenma:/tenma/media -p 8000:8000 hmhrex/tenma`

But no comics are importted. I've tried .cbz, .zip, and jpg files. I checked that I have the correct paths so I'm not sure what the problem is:

```
docker inspect -f '{{ .Mounts }}' 332
[{ /mnt/Data/Comics /tenma/files   true rprivate} { /mnt/Config/Tenma /tenma/media   true rprivate}]
```

**Comment by hmhrex** [comment]
Try running bash inside the container and seeing if the files are accessible there.

1. Execute bash in the container: `docker exec -it [CONTAINER-NAME] bash`
2. See if the files are accessible in the container: `ls /tenma/files`

If you are able to see files, then you should be good to go. If you're not able to see the files, then there's most likely something wrong with your local path. If the files are there, but they're not getting imported, there might be a permission issue.

Let me know what your result of the above actions are and we can see if we can crack this issue. :)

**Comment by hmhrex** [comment]
@g2744092 Did you ever figure out your issue? If so, I can close this issue for you.

**Comment by hmhrex** [comment]
@g2744092 Go ahead and re-open this issue if you're still having this problem.

**Comment by g2744092** [comment]
Figured it out. turned out to be a permission issue.

**Comment by mrkrstphr** [comment]
I'm having this problem. From the docker container, I can see the files:

```
bash-4.3# ls -l /tenma/files/
total 0
drwxr-xr-x   10 root     root           320 Oct  1 18:40 Green Lantern (1990)

bash-4.3# ls -l /tenma/files/Green\ Lantern\ \(1990\)/
total 135408
-rwxr-xr-x    1 root     root      16711917 Feb 17  2017 099.cbz
-rwxr-xr-x    1 root     root      25854912 Feb 17  2017 100.cbz
-rwxr-xr-x    1 root     root      14404187 Feb 17  2017 101.cbz
-rwxr-xr-x    1 root     root      16362504 Feb 17  2017 102.cbz
-rwxr-xr-x    1 root     root      15005885 Feb 17  2017 103.cbz
-rwxr-xr-x    1 root     root      16900003 Feb 17  2017 104.cbz
-rwxr-xr-x    1 root     root      16626584 Feb 17  2017 105.cbz
-rwxr-xr-x    1 root     root      16775950 Feb 17  2017 106.cbz
```

But Tenma doesn't import anything. After clicking the button, the screen just refreshes and says: 

> No series currently available.
